import * as SecureStore from "expo-secure-store";
import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "vi";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, defaultText?: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "vi",
  setLanguage: async () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [language, setLanguageState] = useState<Language>("vi");

  useEffect(() => {
    const loadLang = async () => {
      try {
        const savedLang = await SecureStore.getItemAsync("app_language");
        if (savedLang === "en" || savedLang === "vi") {
          setLanguageState(savedLang as Language);
        }
      } catch (error) {
        console.error("Failed to load language:", error);
      }
    };
    loadLang();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    try {
      await SecureStore.setItemAsync("app_language", lang);
    } catch (error) {
      console.error("Failed to save language:", error);
    }
  };

  const translations: Record<Language, Record<string, string>> = {
    vi: {
      "chat.coach_title": "Health Coach",
      "chat.online_status": "● Đang hoạt động · Powered by Gemini",
      "chat.empty_title": "Xin chào! Tôi là AI Health Coach",
      "chat.empty_subtitle":
        "Tôi đã được trang bị toàn bộ dữ liệu sức khỏe của bạn.\nHãy hỏi tôi bất cứ điều gì về sức khỏe của bạn!",
      "chat.feature_activity": "Vận động",
      "chat.feature_heart": "Nhịp tim",
      "chat.feature_trend": "Xu hướng",
      "chat.feature_health": "Sức khỏe",
      "chat.feature_prompt_activity":
        "Vận động trong 7 ngày qua của tôi như thế nào?",
      "chat.feature_prompt_heart":
        "Chỉ số nhịp tim của tôi trong tuần qua có bình thường không?",
      "chat.feature_prompt_trend":
        "Phân tích xu hướng sức khỏe của tôi trong thời gian gần đây.",
      "chat.feature_prompt_health":
        "Tổng quan tình trạng sức khỏe hiện tại của tôi dựa trên dữ liệu bạn có.",
      "chat.suggested_questions": "Câu hỏi gợi ý",
      "chat.suggest": "Gợi ý",
      "chat.input_placeholder": "Hỏi về sức khỏe của bạn...",
      "chat.quota_exceeded_placeholder": "Đã hết lượt chat hôm nay...",
      "chat.clear_title": "Xóa chat",
      "chat.clear_confirm": "Xóa toàn bộ lịch sử chat?",
      "chat.delete": "Xóa",
      "chat.error_prefix": "Xin lỗi, có lỗi xảy ra:",
      "chat.error_retry": "Vui lòng thử lại hoặc kiểm tra kết nối mạng nhé!",
      "chat.insight_highlights": "💡 Phân tích điểm nhấn:",
      "chat.risk_high": "Rủi ro: Cao",
      "chat.risk_medium": "Rủi ro: Trung bình",
      "chat.risk_low": "Rủi ro: Thấp",
      "chat.premium_feature": "Trợ lý AI (Health Chat)",
      "chat.suggest_q1": "Sức khỏe của tôi tuần này như thế nào?",
      "chat.suggest_q2": "Tôi nên vận động bao nhiêu mỗi ngày?",
      "chat.suggest_q3": "Nhịp tim trung bình của tôi có bình thường không?",
      "chat.suggest_q4": "Tôi có đang đạt mục tiêu bước chân không?",
      "chat.suggest_q5": "Tôi nên ăn gì để giảm cân hiệu quả?",
      "analysis.title_health": "Sức khỏe",
      "analysis.title_analysis": "Phân tích",
      "analysis.title_predict": "Dự đoán",
      "analysis.subtitle": "Báo cáo sức khỏe 7 ngày",
      "analysis.loading": "Đang phân tích dữ liệu sức khỏe bằng AI...",
      "analysis.na": "N/A",
      "analysis.activity_level": "Mức độ vận động của bạn",
      "analysis.steps": "Số bước",
      "analysis.last_7_days": "7 ngày gần nhất",
      "analysis.kcal_burned": "Calo đốt cháy",
      "analysis.active_calories": "Calo vận động",
      "analysis.exercise_time": "Thời gian tập",
      "analysis.minutes_active": "Phút vận động",
      "analysis.heart_rate": "Nhịp tim",
      "analysis.avg_daily_bpm": "BPM trung bình mỗi ngày",
      "analysis.premium_feature": "Phân tích AI (Báo cáo sức khỏe)",
      "home.greeting": "Xin chào",
      "home.city_hcmc": "TP.HCM",
      "home.daily_tracking": "Theo dõi hằng ngày",
      "home.sync_now": "Đồng bộ ngay",
      "home.connect_fit": "Kết nối Fit",
      "home.tutorial_title": "Thiết lập nhanh cho người dùng mới",
      "home.tutorial_text":
        "Nhấn nút Kết nối Fit đang được làm nổi bật để liên kết Google Fit và tự động đồng bộ số bước, quãng đường, calo mỗi ngày.",
      "home.sleep": "Ngủ",
      "home.water": "Nước",
      "home.goal": "Mục tiêu",
      "home.ai_meals": "Bữa ăn AI",
      "home.ai_health_predict": "DỰ ĐOÁN SỨC KHỎE AI",
      "home.system_pulse": "Nhịp sinh học",
      "home.planner": "Lập kế hoạch",
      "home.today_schedules": "LỊCH HÔM NAY",
      "home.manage": "Quản lý",
      "home.no_schedule_today": "Hôm nay chưa có lịch. 🎉",
      "home.medication": "Thuốc",
      "home.medications": "mục thuốc",
      "home.show_less": "Thu gọn",
      "home.show_more": "Xem thêm",
      "home.types": "loại",
      "home.time_slot": "Khung giờ",
      "home.note": "Ghi chú",
      "home.latest_articles": "Bài viết mới",
      "home.view_all": "Xem tất cả",
      "home.health": "Sức khỏe",
      "home.read_article": "Đọc bài",
      "tabs.home": "Trang chủ",
      "tabs.activity": "Hoạt động",
      "tabs.analysis": "Phân tích",
      "tabs.profile": "Profile",
      "profile.my": "My ",
      "profile.profile": "Profile",
      "profile.body_metrics": "Chỉ số cơ thể",
      "profile.update": "Cập nhật",
      "profile.height": "Chiều cao",
      "profile.weight": "Cân nặng",
      "profile.age": "Tuổi",
      "profile.gender": "Giới tính",
      "profile.unit_cm": "cm",
      "profile.unit_kg": "kg",
      "profile.unit_years": "tuổi",
      "profile.account": "Tài khoản",
      "profile.personal_data": "Dữ liệu cá nhân",
      "profile.scan_medical_record": "Quét hồ sơ bệnh án",
      "profile.subscription_plan": "Gói thành viên",
      "auth.common.error": "Lỗi",
      "auth.common.try_again": "Vui lòng thử lại.",
      "auth.verify.title": "Xác thực OTP",
      "auth.verify.subtitle": "Mã xác nhận đã được gửi đến",
      "auth.verify.enter_code": "Nhập mã 6 chữ số",
      "auth.verify.confirm": "Xác nhận",
      "auth.verify.not_received": "Chưa nhận được mã? ",
      "auth.verify.resend": "Gửi lại",
      "auth.verify.resend_after": "Gửi lại sau",
      "auth.verify.security_note":
        "Mã OTP có hiệu lực trong 5 phút. Không chia sẻ mã này với bất kỳ ai.",
      "auth.verify.invalid_otp": "Vui lòng nhập đầy đủ mã OTP 6 chữ số.",
      "auth.verify.resend_success_title": "Đã gửi lại",
      "auth.verify.resend_success_message":
        "Mã OTP mới đã được gửi đến email của bạn.",
      "auth.verify.resend_failed_title": "Gửi lại thất bại",
      "auth.verify.resend_failed_message": "Không thể gửi lại mã OTP.",
      "auth.verify_register.title": "Xác thực OTP Đăng ký",
      "auth.verify_register.confirm_register": "Xác nhận & Đăng ký",
      "auth.verify_register.security_note":
        "Mã OTP có hiệu lực trong 10 phút. Không chia sẻ mã này với bất kỳ ai.",
      "auth.verify_register.invalid_params":
        "Thông tin đăng ký không đầy đủ. Vui lòng thử lại.",
      "auth.verify_register.success_title": "Thành công",
      "auth.verify_register.success_message":
        "Tài khoản đã được tạo! Vui lòng cung cấp một số chỉ số sức khỏe cơ bản.",
      "auth.verify_register.ok": "OK",
      "auth.verify_register.create_failed": "Có lỗi xảy ra khi tạo tài khoản.",
      "auth.reset.title": "Đặt mật khẩu mới",
      "auth.reset.subtitle":
        "Tạo mật khẩu mới cho tài khoản của bạn. Hãy chọn mật khẩu mạnh và dễ nhớ.",
      "auth.reset.new_password": "Mật khẩu mới",
      "auth.reset.new_password_placeholder": "Nhập mật khẩu mới",
      "auth.reset.confirm_password_placeholder": "Nhập lại mật khẩu",
      "auth.reset.password_not_match": "Mật khẩu không khớp",
      "auth.reset.requirements": "Yêu cầu mật khẩu:",
      "auth.reset.requirement_min_6": "Ít nhất 6 ký tự",
      "auth.reset.requirement_uppercase": "Có chữ hoa (khuyến khích)",
      "auth.reset.requirement_number": "Có chữ số (khuyến khích)",
      "auth.reset.confirm_button": "Xác nhận đặt lại mật khẩu",
      "auth.reset.password_min_length": "Mật khẩu phải có ít nhất 6 ký tự.",
      "auth.reset.password_mismatch": "Mật khẩu xác nhận không khớp.",
      "auth.reset.success_title": "Thành công",
      "auth.reset.success_message":
        "Mật khẩu của bạn đã được đặt lại thành công. Vui lòng đăng nhập lại.",
      "auth.reset.failed_title": "Đặt lại thất bại",
      "auth.reset.invalid_otp": "Mã OTP không hợp lệ hoặc đã hết hạn.",
      "auth.reset.strength_weak": "Yếu",
      "auth.reset.strength_medium": "Trung bình",
      "auth.reset.strength_strong": "Mạnh",
      "auth.reset.strength_very_strong": "Rất mạnh",
      "auth.register.subtitle": "Tham gia Healthcare Now ngay hôm nay",
      "auth.register.full_name_label": "Họ và tên",
      "auth.register.full_name_placeholder": "Nguyen Van A",
      "auth.register.confirm_password_label": "Xác nhận mật khẩu",
      "auth.register.validation_all_fields": "Vui lòng điền đầy đủ thông tin",
      "auth.register.validation_password_mismatch":
        "Mật khẩu xác nhận không khớp",
      "auth.register.failed_title": "Đăng ký thất bại",
      "auth.register.email_exists":
        "Email này đã được đăng ký. Vui lòng dùng email khác.",
      "auth.register.send_otp_failed": "Có lỗi khi gửi OTP.",
      "auth.register.have_account": "Đã có tài khoản? ",
      "auth.forgot.title": "Quên mật khẩu",
      "auth.forgot.subtitle":
        "Nhập địa chỉ email đã đăng ký. Chúng tôi sẽ gửi mã xác nhận đến email của bạn.",
      "auth.forgot.validation_email_required":
        "Vui lòng nhập địa chỉ email của bạn.",
      "auth.forgot.send_failed_title": "Gửi mã thất bại",
      "auth.forgot.send_failed_message":
        "Không thể gửi mã OTP. Vui lòng thử lại.",
      "auth.forgot.send_code": "Gửi mã xác nhận",
      "auth.forgot.back_login": "Quay lại đăng nhập",
      "auth.login.subtitle": "Người bạn đồng hành sức khỏe số toàn diện",
      "auth.login.email_label": "Địa chỉ email",
      "auth.login.email_placeholder": "example@email.com",
      "auth.login.password_label": "Mật khẩu",
      "auth.login.sign_in": "Đăng nhập",
      "auth.login.forgot_password": "Quên mật khẩu?",
      "auth.login.or": "HOẶC",
      "auth.login.continue_google": "Tiếp tục với Google",
      "auth.login.no_account": "Bạn chưa có tài khoản? ",
      "auth.login.sign_up": "Đăng ký",
      "auth.login.validation_missing": "Vui lòng nhập email và mật khẩu",
      "auth.login.failed_title": "Đăng nhập thất bại",
      "auth.login.failed_message": "Kiểm tra lại thông tin và thử lại.",
      "auth.login.google_failed_title": "Đăng nhập Google thất bại",
      "auth.login.google_token_error": "Không thể lấy Google ID Token",
      "auth.login.google_error_title": "Lỗi đăng nhập Google",
      "settings.title": "Cài đặt",
      "settings.account": "TÀI KHOẢN",
      "settings.personal_info": "Thông tin cá nhân",
      "settings.notifications": "Thông báo",
      "settings.change_password": "Đổi mật khẩu",
      "settings.security_privacy": "Bảo mật & Quyền riêng tư",
      "settings.preferences": "TÙY CHỈNH",
      "settings.dark_mode": "Chế độ tối",
      "settings.language": "Ngôn ngữ",
      "settings.logout": "Đăng xuất",
      "settings.premium": "Thành viên Premium",
      "settings.new_user": "Người dùng mới",
      "settings.upload_success_title": "Thành công",
      "settings.upload_success_message": "Cập nhật ảnh đại diện thành công!",
      "settings.upload_error_title": "Lỗi",
      "settings.upload_error_message": "Không thể tải ảnh đại diện lên.",
      "settings.language_pick_message": "Chọn ngôn ngữ bạn muốn sử dụng",
      "settings.language_confirm_title": "Xác nhận đổi ngôn ngữ",
      "settings.language_confirm_message":
        "Ứng dụng sẽ khởi động lại để áp dụng ngôn ngữ mới.",
      "settings.confirm": "Xác nhận",
      "settings.cancel": "Hủy",
      "notifications.title": "Thông báo",
      "notifications.processing": "Đang xử lý...",
      "notifications.mark_all_read": "Đọc tất cả",
      "notifications.tab_unread": "Chưa đọc",
      "notifications.tab_read": "Đã đọc",
      "notifications.empty": "Chưa có thông báo nào.",
      "notifications.success_title": "Thành công",
      "notifications.success_message":
        "Đã gửi thông báo nhắc nhở luyện tập đến điện thoại!",
      "notifications.error_title": "Lỗi",
      "notifications.error_message": "Không thể gửi thông báo thử nghiệm.",
      "notifications.mark_all_error": "Không thể đánh dấu đã đọc tất cả.",
      "security.title": "Bảo mật & Quyền riêng tư",
      "security.account_auth_section": "TÀI KHOẢN & XÁC THỰC",
      "security.change_password": "Đổi mật khẩu",
      "security.change_password_subtitle":
        "Cập nhật mật khẩu định kỳ để bảo vệ tài khoản",
      "security.change_email": "Thay đổi email",
      "security.change_email_subtitle": "Cập nhật email đăng nhập của bạn",
      "security.biometric": "Xác thực sinh trắc học",
      "security.biometric_subtitle": "Sử dụng vân tay hoặc Face ID thay vì OTP",
      "security.auto_google_fit": "Tự động kết nối Google Fit",
      "security.auto_google_fit_subtitle":
        "Bỏ qua yêu cầu xác nhận khi đồng bộ dữ liệu sức khỏe",
      "security.security_alerts_section": "THÔNG BÁO BẢO MẬT",
      "security.login_alert": "Cảnh báo đăng nhập lạ",
      "security.login_alert_subtitle":
        "Nhận thông báo và yêu cầu đổi mật khẩu khi có thiết bị lạ",
      "security.data_account_section": "DỮ LIỆU & TÀI KHOẢN",
      "security.export_google_fit": "Xuất dữ liệu Google Fit",
      "security.export_google_fit_subtitle":
        "Tải xuống dữ liệu dưới định dạng JSON/XML",
      "security.privacy_policy": "Chính sách quyền riêng tư",
      "security.privacy_policy_subtitle":
        "Xem chính sách bảo mật và điều khoản dịch vụ",
      "security.delete_account": "Xóa tài khoản",
      "security.delete_account_subtitle":
        "Vô hiệu hóa vĩnh viễn tài khoản người dùng",
      "security.hero_title": "Tài khoản của bạn được bảo vệ",
      "security.hero_subtitle":
        "Quản lý quyền truy cập và bảo mật thông tin cá nhân của bạn.",
      "security.notification": "Thông báo",
      "security.auto_fit_enabled":
        "Đã bật tự động kết nối Google Fit. Bạn sẽ không bị hỏi lại.",
      "security.auto_fit_disabled":
        "Đã tắt tự động kết nối Google Fit. Bạn sẽ cần xác nhận ở lần tới.",
      "security.delete_confirm_title": "⚠️ Xóa tài khoản",
      "security.delete_confirm_message":
        "Hành động này sẽ vô hiệu hóa tài khoản của bạn. Bạn không thể đăng nhập lại. Bạn có chắc chắn muốn xóa tài khoản?",
      "security.delete_confirm_button": "Xóa vĩnh viễn",
      "security.delete_success_message":
        "Tài khoản của bạn đã được vô hiệu hóa.",
      "security.export_format_title": "Định dạng xuất dữ liệu",
      "security.export_format_message":
        "Bạn muốn tải dữ liệu Google Fit dưới định dạng nào?",
      "security.export_json": "JSON",
      "security.export_xml": "XML",
      "security.export_json_message": "Dữ liệu JSON đang được tải xuống...",
      "security.export_xml_message": "Dữ liệu XML đang được tải xuống...",
      "security.policy_title": "Chính sách & Quyền riêng tư",
      "security.policy_content":
        "1. Thu thập dữ liệu: Chúng tôi chỉ thu thập dữ liệu Google Fit nhằm cung cấp biểu đồ và đánh giá sức khỏe.\n2. Bảo mật: Dữ liệu của bạn được mã hóa an toàn.\n3. Quyền của bạn: Bạn có quyền yêu cầu xóa toàn bộ dữ liệu bất kỳ lúc nào.",
      "security.feature_developing": "Chức năng đang phát triển.",
      "security.cancel": "Hủy",
      "security.error_no_data": "Không có dữ liệu sức khỏe để xuất.",
      "security.sharing_unavailable": "Tính năng chia sẻ không khả dụng trên thiết bị này.",
      "security.error": "Lỗi",
      "change_password.title": "Đổi mật khẩu",
      "change_password.step1_subtitle":
        "Nhập mật khẩu hiện tại của bạn để nhận OTP xác thực.",
      "change_password.step2_subtitle":
        "Chúng tôi đã gửi mã OTP 6 chữ số đến email của bạn. Vui lòng nhập nó bên dưới.",
      "change_password.step3_subtitle":
        "Bây giờ nhập mật khẩu mới của bạn để hoàn thành cập nhật.",
      "change_password.current_password": "Mật khẩu hiện tại",
      "change_password.password_placeholder": "••••••••",
      "change_password.forgot_password": "Quên mật khẩu?",
      "change_password.send_otp": "Gửi OTP",
      "change_password.verify_identity": "Xác minh danh tính",
      "change_password.enter_code":
        "Nhập mã 6 chữ số được gửi đến email của bạn ",
      "change_password.resend_code_in": "Gửi lại mã trong ",
      "change_password.resend_otp": "Chưa nhận được mã? Gửi lại OTP",
      "change_password.verify_now": "Xác minh ngay",
      "change_password.new_password": "Mật khẩu mới",
      "change_password.confirm_password": "Xác nhận mật khẩu mới",
      "change_password.update_password": "Cập nhật mật khẩu",
      "change_password.error": "Lỗi",
      "change_password.enter_current":
        "Vui lòng nhập mật khẩu hiện tại của bạn",
      "change_password.profile_not_found":
        "Hồ sơ người dùng hoặc email không tìm thấy",
      "change_password.send_otp_failed":
        "Không thể gửi OTP. Kiểm tra mật khẩu hiện tại của bạn.",
      "change_password.fill_all_fields":
        "Vui lòng điền đầy đủ tất cả các trường",
      "change_password.profile_not_loaded":
        "Hồ sơ người dùng chưa được tải. Vui lòng thử lại.",
      "change_password.passwords_not_match": "Mật khẩu không khớp",
      "change_password.success": "Thành công",
      "change_password.success_message":
        "Mật khẩu đã được thay đổi thành công!",
      "change_password.change_failed":
        "OTP không hợp lệ hoặc không thể thay đổi mật khẩu.",
      "change_password.resend_success":
        "Mã OTP mới đã được gửi đến email của bạn.",
      "change_password.resend_failed": "Không thể gửi lại OTP.",
      "change_password.invalid_otp": "Vui lòng nhập mã OTP 6 chữ số",
      "change_password.ok": "OK",
      "change_email.title": "Thay đổi email",
      "change_email.step1_subtitle": "Cập nhật email mới để tiếp tục sử dụng dịch vụ.",
      "change_email.step2_subtitle": "Vui lòng nhập mã OTP đã được gửi đến email mới của bạn.",
      "change_email.new_email": "Email mới",
      "change_email.email_placeholder": "example@email.com",
      "change_email.current_password": "Mật khẩu xác nhận",
      "change_email.password_placeholder": "••••••••",
      "change_email.send_otp": "Nhận mã OTP",
      "change_email.verify_now": "Xác nhận thay đổi",
      "change_email.error": "Lỗi",
      "change_email.invalid_email": "Email không hợp lệ",
      "change_email.enter_password": "Vui lòng nhập mật khẩu xác nhận",
      "change_email.send_otp_failed": "Không thể gửi mã OTP đến email này.",
      "change_email.success": "Thành công",
      "change_email.success_message": "Email của bạn đã được thay đổi thành công!",
      "change_email.change_failed": "Mã OTP không đúng hoặc email đã tồn tại.",
      "change_email.google_title": "Đổi email Google",
      "change_email.google_subtitle": "Bạn đang đăng nhập bằng Google. Vui lòng chọn tài khoản Google mới để thay đổi email.",
      "change_email.google_btn": "Chọn tài khoản Google mới",
      "change_email.google_success": "Đã cập nhật email Google thành công!",
      "change_email.google_failed": "Không thể đổi email Google.",
      "personal_data.title": "Dữ liệu cá nhân",
      "personal_data.info_text":
        "Dưới đây là dữ liệu Google Fit được đồng bộ của bạn cho hôm nay ({date}).\nPhần này sử dụng thời gian chuyển động từ Google Fit và không phụ thuộc vào nhật ký bài tập trong ứng dụng.",
      "personal_data.loading": "Đang tải chỉ số sức khỏe...",
      "personal_data.error": "Không thể tải dữ liệu sức khỏe.",
      "personal_data.steps": "Bước chân",
      "personal_data.distance": "Quãng đường",
      "personal_data.heart_rate": "Nhịp tim",
      "personal_data.resting_hr": "Nhịp tim nghỉ",
      "personal_data.active_calories": "Calo vận động",
      "personal_data.total_energy": "Năng lượng tổng",
      "personal_data.sleep_duration": "Thời gian ngủ",
      "personal_data.movement_time": "Thời gian chuyển động",
      "personal_data.unit_steps": "bước",
      "personal_data.unit_bpm": "lần/phút",
      "personal_data.unit_kcal": "kcal",
      "personal_data.unit_km": "km",
      "personal_data.unit_h": "giờ",
      "personal_data.unit_m": "phút",
      "personal_data.unit_meter": "m",
      "activity.hub": "Trung tâm Hoạt động",
      "activity.settings": "Cài đặt",
      "activity.steps": "Bước chân",
      "activity.calories": "Calo",
      "activity.goal": "Mục tiêu",
      "activity.save_goals": "Lưu mục tiêu",
      "activity.edit_goals": "Chỉnh sửa mục tiêu",
      "activity.burned": "Calo đã đốt",
      "activity.start": "Bắt đầu hoạt động",
      "activity.running": "Chạy bộ",
      "activity.outdoor": "Ngoài trời",
      "activity.gym": "Tập Gym",
      "activity.indoor": "Trong nhà",
      "activity.stretching": "Giãn cơ",
      "activity.yoga": "Yoga",
      "activity.set_goals": "Thiết lập mục tiêu",
      "activity.steps_goal": "Mục tiêu bước chân",
      "activity.calories_goal": "Mục tiêu Calo (kcal)",
      "activity.steps_placeholder": "Ví dụ: 10000",
      "activity.calories_placeholder": "Ví dụ: 500",
      "activity.save": "Lưu",
      "activity.cancel": "Hủy",
      "activity.details_title": "Hoạt động thể chất",
      "activity.aerobic": "Tim mạch",
      "activity.flexibility": "Linh hoạt",
      "activity.recovery": "Phục hồi",
      "activity.strength": "Sức mạnh",
      "activity.total_dist": "Tổng quãng đường",
      "activity.avg_speed": "Tốc độ TB",
      "activity.exercise_time": "Thời gian tập",
      "activity.start_btn": "Bắt đầu",
      "hydration.title": "Cấp nước",
      "hydration.today": "Hôm nay",
      "hydration.quick_add": "THÊM NHANH",
      "hydration.recent_activity": "HOẠT ĐỘNG GẦN ĐÂY",
      "hydration.view_all": "Xem tất cả",
      "hydration.no_logs": "Chưa có bản ghi nào hôm nay.",
      "hydration.goal": "Mục tiêu",
      "hydration.ml": "ml",
      "hydration.custom": "Tùy chỉnh",
      "sleep.title": "Giấc ngủ",
      "sleep.score": "ĐIỂM NGỦ",
      "sleep.total_duration": "TỔNG THỜI GIAN",
      "sleep.deep_sleep": "NGỦ SÂU",
      "sleep.relaxing_sounds": "Âm thanh thư giãn",
      "sleep.view_all": "Xem tất cả",
      "sleep.smart_alarm": "Báo thức thông minh",
      "sleep.excellent": "Xuất sắc",
      "sleep.good": "Tốt",
      "sleep.fair": "Trung bình",
      "sleep.add_alarm": "Thêm báo thức",
      "sleep.no_alarms": "Chưa có báo thức nào",
      "sleep.rain": "Mưa",
      "sleep.forest": "Rừng",
      "sleep.wave": "Sóng",
      "meal.title": "Lịch ăn uống",
      "meal.ai_nutritionist": "Chuyên gia dinh dưỡng AI",
      "meal.scientific_diet_planning": "Lập kế hoạch ăn uống khoa học",
      "meal.my_meal_plan": "Kế hoạch ăn uống của tôi",
      "meal.activities": "Hoạt động",
      "meal.generate_plan": "Tạo kế hoạch",
      "meal.generating": "Đang tạo...",
      "meal.breakfast": "Bữa sáng",
      "meal.lunch": "Bữa trưa",
      "meal.dinner": "Bữa tối",
      "meal.snacks": "Ăn nhẹ",
      "meal.estimated_calories": "Calo ước tính",
      "meal.no_history": "Chưa có lịch sử nào",
      "meal.quota_exceeded": "Đã hết hạn mức tạo kế hoạch hôm nay",
      "meal.running": "Chạy bộ",
      "meal.walking": "Đi bộ",
      "meal.yoga": "Yoga",
      "meal.gym": "Tập gym",
      "meal.cycling": "Đạp xe",
      "meal.delete_history": "Xóa khỏi lịch sử",
      "meal.clear_all": "Xóa tất cả",
      "meal.delete_confirm": "Xóa kế hoạch này khỏi lịch sử?",
      "meal.clear_all_confirm": "Xóa tất cả lịch sử kế hoạch ăn AI?",
      "meal.cancel": "Hủy",
      "meal.delete": "Xóa",
      "meal.clear": "Xóa",
      "meal.personal_metrics": "Chỉ số cá nhân",
      "meal.weight": "Cân nặng",
      "meal.height": "Chiều cao",
      "meal.age": "Tuổi",
      "meal.gender": "Giới tính",
      "meal.steps_label": "Bước",
      "meal.distance_label": "Quãng đường",
      "meal.male": "Nam",
      "meal.female": "Nữ",
      "meal.choose_activity": "Chọn hoạt động",
      "meal.select_at_least_one": "Vui lòng chọn ít nhất một hoạt động",
      "meal.plan_history": "Lịch sử kế hoạch",
      "meal.saved_plans": "kế hoạch đã lưu",
      "meal.no_saved_plans": "Chưa có kế hoạch ăn uống nào",
      "meal.generate_automatic":
        "Tạo kế hoạch và nó sẽ tự động xuất hiện ở đây",
      "meal.past_plan": "Kế hoạch cũ",
      "meal.view_btn": "Xem",
      "meal.update_stats": "Cập nhật chỉ số của bạn để có độ chính xác cao",
      "meal.restricted_ingredients": "Thành phần hạn chế",
      "meal.ai_exclude": "AI sẽ loại bỏ",
      "meal.total_tdee": "Tổng năng lượng tiêu thụ (TDEE)",
      "meal.protein": "Đạm",
      "meal.carbs": "Tinh bột",
      "meal.fat": "Chất béo",
      "meal.quantified_meals": "Bữa ăn định lượng",
      "meal.recalculate": "Tính toán lại chỉ số",
      "article.title": "Tất cả bài viết",
      "article.loading": "Đang tải...",
      "article.health": "Sức khỏe",
      "article.no_articles": "Chưa có bài viết nào.",
      "article.error": "Lỗi lấy danh sách bài viết",
      "article.details": "Chi tiết bài viết",
      "article.back": "Quay lại",
      "article.not_found": "Không tìm thấy bài viết",
      "article.read_time": "phút đọc",
      "article.by": "bởi",
      "article.ai_expert": "Chuyên gia dinh dưỡng",
      "article.summary": "Tóm tắt",
      "article.content": "Nội dung",
      "article.no_content": "Chưa có nội dung chi tiết",
      "article.bookmark": "Lưu",
      "article.bookmarked": "Đã lưu",
      "schedule.title": "Lịch làm việc",
      "schedule.manage": "Quản lý lịch",
      "schedule.new": "Lịch mới",
      "schedule.add": "Thêm lịch",
      "schedule.edit": "Chỉnh sửa",
      "schedule.delete": "Xóa",
      "schedule.date": "Ngày",
      "schedule.time": "Giờ",
      "schedule.description": "Mô tả",
      "schedule.save": "Lưu",
      "schedule.cancel": "Hủy",
      "schedule.no_schedules": "Chưa có lịch nào",
      "schedule.confirm_delete": "Xóa lịch này?",
      "sleep.alarm": "Báo thức",
      "sleep.alarms": "Báo thức",
      "sleep.set_alarm": "Đặt báo thức",
      "sleep.edit_alarm": "Chỉnh sửa báo thức",
      "sleep.delete_alarm": "Xóa báo thức",
      "sleep.time": "Giờ",
      "sleep.label": "Tên",
      "sleep.repeat": "Lặp lại",
      "sleep.enabled": "Bật",
      "sleep.disabled": "Tắt",
      "sleep.music": "Nhạc ngủ",
      "sleep.upload_music": "Tải nhạc",
      "sleep.no_music": "Chưa có nhạc nào",
      "sleep.duration": "Thời lượng",
      "sleep.quality": "Chất lượng",
      "running.title": "Chạy bộ",
      "running.start": "Bắt đầu",
      "running.stop": "Dừng",
      "running.pause": "Tạm dừng",
      "running.resume": "Tiếp tục",
      "running.distance": "Quãng đường",
      "running.time": "Thời gian",
      "running.calories": "Calo",
      "running.speed": "Tốc độ",
      "running.pace": "Nhịp độ",
      "running.summary": "Tóm tắt chạy bộ",
      "running.save": "Lưu",
      "gym.title": "Tập gym",
      "gym.exercise": "Bài tập",
      "gym.sets": "Hiệp",
      "gym.reps": "Lần",
      "gym.weight": "Trọng lượng",
      "gym.start": "Bắt đầu",
      "gym.end": "Kết thúc",
      "gym.summary": "Tóm tắt tập gym",
      "yoga.title": "Yoga",
      "yoga.exercise": "Bài tập",
      "yoga.duration": "Thời lượng",
      "yoga.start": "Bắt đầu",
      "yoga.end": "Kết thúc",
      "yoga.summary": "Tóm tắt yoga",
      "stretching.title": "Giãn cơ",
      "stretching.exercise": "Bài tập",
      "stretching.duration": "Thời lượng",
      "stretching.start": "Bắt đầu",
      "stretching.end": "Kết thúc",
      "stretching.summary": "Tóm tắt giãn cơ",
      "subscription.title": "Gói thành viên",
      "subscription.plans": "Các gói",
      "subscription.current": "Gói hiện tại",
      "subscription.free": "Miễn phí",
      "subscription.premium": "Premium",
      "subscription.upgrade": "Nâng cấp",
      "subscription.cancel": "Hủy",
      "subscription.expired": "Hết hạn",
      "subscription.days_left": "ngày còn lại",
      "premium.limit_reached": "Đã đạt giới hạn",
      "premium.upgrade_now": "Nâng cấp ngay",
      "premium.later": "Để sau",
      "premium.description": "Bạn đã đạt đến giới hạn số lần sử dụng cho {featureName}. Nâng cấp lên Premium để mở khóa không giới hạn và cải thiện hành trình sức khỏe của bạn.",
      "premium.feature_ai_analysis": "Phân tích AI không giới hạn",
      "premium.feature_ai_analysis_sub": "Đi sâu vào từng chỉ số, mỗi ngày.",
      "premium.feature_ai_assistant": "Trợ lý sức khỏe 24/7",
      "premium.feature_ai_assistant_sub": "Truy cập trợ lý AI y tế mọi lúc mọi nơi.",
      "premium.feature_health_plans": "Kế hoạch sức khỏe cá nhân",
      "premium.feature_health_plans_sub": "Thói quen hàng ngày được thiết kế riêng cho bạn.",
      "medical.scan": "Quét y tế",
      "medical.upload": "Tải lên",
      "medical.delete": "Xóa",
      "medical.no_records": "Chưa có hồ sơ nào",
      "medical.error": "Lỗi",
      "medical.notice": "Thông báo",
      "medication.title": "Lịch thuốc",
      "medication.add": "Thêm thuốc",
      "medication.edit": "Chỉnh sửa",
      "medication.delete": "Xóa",
      "medication.name": "Tên thuốc",
      "medication.dosage": "Liều lượng",
      "medication.frequency": "Tần suất",
      "medication.time": "Giờ",
      "medication.notes": "Ghi chú",
      "medication.save": "Lưu",
      "medication.cancel": "Hủy",
      "medication.no_medications": "Chưa có thuốc nào",
      "schedule.active_schedules": "lịch trình đang hoạt động",
      "schedule.done": "Xong",
      "schedule.select_all": "Chọn Tất Cả",
      "schedule.delete_count": "Xóa ({count})",
      "schedule.details": "Chi Tiết",
      "schedule.more": "thêm",
      "schedule.new_subtitle": "Thiết kế lộ trình tập luyện của riêng bạn",
      "schedule.select_type": "CHỌN LOẠI HOẠT ĐỘNG",
      "schedule.set_frequency": "THIẾT LẬP TẦN SUẤT",
      "schedule.daily": "Hàng Ngày",
      "schedule.weekly": "Hàng Tuần",
      "schedule.custom": "Tùy Chỉnh",
      "schedule.select_days": "CHỌN NGÀY",
      "schedule.set_time": "THIẾT LẬP THỜI GIAN",
      "schedule.set_goal": "THIẾT LẬP MỤC TIÊU",
      "schedule.goal_required":
        "Mục tiêu là bắt buộc. Vui lòng nhập mục tiêu tập luyện của bạn.",
      "schedule.missing_goal": "Thiếu mục tiêu",
      "schedule.missing_goal_msg":
        "Bạn cần nhập mục tiêu trước khi tạo lịch tập.",
      "schedule.missing_days": "Thiếu ngày tập",
      "schedule.missing_days_msg": "Vui lòng chọn ít nhất 1 ngày tập.",
      "schedule.success_msg": "Lịch tập luyện được lưu thành công!",
      "schedule.error_msg": "Không thể lưu lịch tập. Vui lòng thử lại.",
      "schedule.creating": "Đang tạo...",
      "schedule.create": "Tạo Lịch Trình",
      "running.gps_active": "GPS ĐANG HOẠT ĐỘNG",
      "running.elapsed_time": "THỜI GIAN ĐÃ QUA",
      "running.save_error": "Lỗi trong quá trình lưu! Vui lòng thử lại.",
      "running.permission_error":
        "Cần quyền truy cập để lưu hình ảnh lộ trình của bạn.",
      "running.share_title": "Xem kết quả chạy của tôi trên HealthCareNow!",
      "running.save_success":
        "Tuyệt vời! Bản đồ lộ trình đã được lưu vào Thư viện ảnh của bạn.",
      "running.completed": "Hoàn Thành Chạy!",
      "running.completed_subtitle_map": "Làm tốt lắm. Đây là lộ trình của bạn.",
      "running.completed_subtitle_trophy":
        "Làm tốt lắm. Bạn đang khỏe mạnh hơn mỗi ngày.",
      "running.total_distance": "TỔNG QUÃNG ĐƯỜNG",
      "running.share": "Chia Sẻ / Lưu Bản Đồ",
      "running.discard": "Hủy Bỏ",
      "subscription.plans_subtitle":
        "Khai phá tiềm năng sức khỏe tối đa với Premium.",
      "subscription.active_plan": "ĐANG KÍCH HOẠT",
      "subscription.recommended": "KHUYÊN DÙNG",
      "subscription.all_features_active": "Tất cả tính năng đã được kích hoạt",
      "subscription.complete_upgrade": "Hoàn Tất Nâng Cấp",
      "subscription.billed_once": "Thanh toán một lần",
      "subscription.lifetime_unlocked": "Đã mở khóa quyền truy cập vĩnh viễn",
      "subscription.pay_once": "Thanh toán một lần, dùng mãi mãi",
      "subscription.select_method": "Chọn phương thức thanh toán",
      "subscription.confirm_pay": "Xác nhận & Thanh toán",
      "subscription.secure_ssl": "MÃ HÓA SSL BẢO MẬT",
      "subscription.feature_analysis": "Phân tích sức khỏe AI không giới hạn",
      "subscription.feature_meals": "Kế hoạch ăn uống AI không giới hạn",
      "subscription.feature_chat": "Trò chuyện sức khỏe AI không giới hạn",
      "subscription.feature_scans": "Quét hồ sơ y tế không giới hạn",
      "subscription.feature_reports": "Báo cáo sinh trắc học nâng cao",
      "subscription.feature_basic_tracking": "Theo dõi hoạt động cơ bản",
      "subscription.feature_limited_insights": "Phân tích sức khỏe cơ bản",
      "subscription.feature_standard_support": "Hỗ trợ tiêu chuẩn",
      "medical.scan_title": "Quét hồ sơ y tế",
      "medical.ai_feature_name": "AI Medical Scan",
      "medical.no_image": "Chưa chọn hình ảnh",
      "medical.analyzing": "AI đang phân tích hồ sơ...",
      "medical.gallery": "Thư viện",
      "medical.take_photo": "Chụp ảnh",
      "medical.diagnosis": "Chẩn đoán",
      "medical.medications_count": "Thuốc được kê đơn ({count})",
      "medical.medication_times": "Thời gian uống thuốc:",
      "medical.forbidden_foods_list": "Danh sách thực phẩm kiêng kỵ",
      "medical.schedule_reminders": "Lên lịch nhắc nhở",
      "medical.history": "Lịch sử y tế",
      "medical.active_medication": "Đang điều trị",
      "medical.expired_label": "Đã hết hạn",
      "medical.reminders_disabled": "Đã xóa tất cả nhắc nhở cho hồ sơ này.",
      "medical.reminders_enabled": "Đã tạo lại các nhắc nhở uống thuốc.",
      "medical.duration": "Thời gian:",
      "medical.disable": "Vô hiệu",
      "medical.enable": "Kích hoạt",
      "medical.details": "Chi tiết",
      "medical.expire_btn": "Hết hạn",
      "medical.forbidden_foods_btn": "Thực phẩm kiêng kỵ",
      "medical.permission": "Quyền truy cập",
      "medical.camera_permission_msg":
        "Cần cấp quyền camera/thư viện để chụp hoặc chọn ảnh đơn thuốc.",
      "medical.parse_error": "Lỗi xử lý dữ liệu",
      "medical.unknown_title": "Không thể nhận dạng",
      "medical.unknown_msg":
        "AI không thể phân tích được hình ảnh này. Vui lòng chụp lại ảnh rõ hơn (đủ ánh sáng, không bị mờ, đúng góc chụp đơn thuốc).",
      "medical.ai_error": "Lỗi AI",
      "medical.send_error":
        "Không thể gửi ảnh đến máy chủ AI. Vui lòng thử lại.",
      "medical.default_title": "Hồ sơ y tế",
      "medical.notif_permission": "Quyền thông báo",
      "medical.notif_permission_msg":
        "Hồ sơ đã lưu, nhưng vui lòng bật thông báo để nhận lời nhắc uống thuốc.",
      "medical.notif_title": "💊 Nhắc nhở uống thuốc",
      "medical.notif_body": "Đã đến giờ uống {name} ({dosage})",
      "medical.no_meds_schedule":
        "Không tìm thấy thuốc nào để lên lịch nhắc nhở.",
      "medical.save_success":
        "Đã lưu hồ sơ y tế và tạo nhắc nhở cho {count} loại thuốc!",
      "medical.save_error": "Không thể lưu hồ sơ hoặc tạo nhắc nhở.",
      "medical.confirm": "Xác nhận",
      "medical.expire_confirm_msg":
        "Đánh dấu hồ sơ này là đã hết hạn/đã khỏi bệnh?",
      "medical.cancel_action": "Hủy",
      "medical.expire_success":
        "Hồ sơ đã hết hạn và các nhắc nhở đã được dọn dẹp.",
      "medical.expire_error":
        "Không thể cập nhật trạng thái hoặc dọn dẹp nhắc nhở.",
      "common.mon": "Th 2",
      "common.tue": "Th 3",
      "common.wed": "Th 4",
      "common.thu": "Th 5",
      "common.fri": "Th 6",
      "common.sat": "Th 7",
      "common.sun": "CN",
      "common.already_premium": "Đã là Premium",
      "common.already_premium_msg": "Bạn đã là thành viên Premium rồi! 🎉",
      "common.failed_create_order": "Không thể tạo đơn hàng thanh toán.",
      "common.payment_success":
        "Thanh toán thành công! Tài khoản của bạn đang được nâng cấp.",
      "common.cancelled": "Đã hủy",
      "common.payment_cancelled": "Thanh toán đã bị hủy.",
      "meal.bmr": "Chuyển hóa cơ bản (BMR)",
      "meal.kcal": "kcal",
      "meal.dose": "liều",
      "subscription.premium_lifetime": "Gói Premium Vĩnh Viễn",
      "subscription.life_period": "TRỌN ĐỜI",
      "subscription.select_payment": "Chọn phương thức thanh toán",
      "subscription.apple_pay": "Apple Pay",
      "subscription.google_pay": "Google Pay",
      "subscription.payos_method": "PayOS (QR / Chuyển khoản)",
      "subscription.secure_gateway": "Cổng thanh toán nhanh & bảo mật",
      "subscription.all_vn_banks": "Tất cả ngân hàng Việt Nam",
      "subscription.vietqr": "VietQR",
      "subscription.payos_checkout": "Thanh toán PayOS",
      "subscription.browser_unavailable": "Trình duyệt nội bộ không khả dụng.",
      "subscription.open_browser": "Mở bằng trình duyệt",
      "subscription.price_free": "$0",
      "subscription.forever": "/ mãi mãi",
      "subscription.one_time": "/ một lần",
      "subscription.price_premium": "10,000đ",
      "medical.retake": "Chụp lại",
      "medical.close": "Đóng",
      "medical.unit_dose": "liều",
      "running.duration": "THỜI GIAN",
      "running.avg_pace": "NHỊP ĐỘ TB",
      "running.save_activity": "Lưu hoạt động",
      "metrics.title": "Chỉ số của bạn",
      "metrics.subtitle": "Hãy giúp chúng tôi cá nhân hóa hành trình sức khỏe của bạn",
      "metrics.full_name": "Họ và tên",
      "metrics.weight": "Cân nặng",
      "metrics.height": "Chiều cao",
      "metrics.sleep_goal": "Mục tiêu ngủ",
      "metrics.steps_goal": "Mục tiêu bước chân",
      "metrics.calories_goal": "Mục tiêu Calo",
      "metrics.dob": "Ngày sinh",
      "metrics.gender": "Giới tính",
      "metrics.male": "Nam",
      "metrics.female": "Nữ",
      "metrics.other": "Khác",
      "metrics.activity_level": "Mức độ hoạt động",
      "metrics.activity_sedentary": "Ít vận động",
      "metrics.activity_lightly": "Vận động nhẹ",
      "metrics.activity_moderately": "Vận động vừa phải",
      "metrics.activity_very": "Vận động nhiều",
      "metrics.complete": "Hoàn tất hồ sơ",
      "metrics.saving": "Đang lưu...",
      "metrics.skip": "Để sau (Về trang chủ)",
      "metrics.error": "Lỗi",
      "metrics.fill_required": "Vui lòng điền cân nặng và chiều cao",
      "metrics.success": "Thành công",
      "metrics.save_success": "Đã lưu chỉ số! Chào mừng bạn đến với Healthcare Now.",
      "metrics.get_started": "Bắt đầu ngay",
      "metrics.save_failed": "Lưu chỉ số thất bại.",
      "metrics.invalid_input": "Dữ liệu không hợp lệ. Vui lòng kiểm tra lại.",
      "sleep.alarm_setup_title": "Đặt báo thức",
      "sleep.smart_alarm_desc": "Đánh thức trong pha ngủ nông",
      "sleep.repeat_title": "LẶP LẠI",
      "sleep.choose_ringtone": "CHỌN NHẠC CHUÔNG",
      "sleep.start_sleeping": "Bắt đầu ngủ",
      "sleep.saving": "Đang lưu...",
      "sleep.prediction_prefix": "Nếu ngủ bây giờ, bạn sẽ có",
      "sleep.prediction_suffix": "thời lượng ngủ",
      "sleep.every_day": "Mỗi ngày",
      "sleep.once": "Chỉ 1 lần",
      "sleep.weekdays": "Ngày thường",
      "sleep.weekends": "Cuối tuần",
      "sleep.notif_permission_msg": "Vui lòng cấp quyền thông báo để chuông báo thức có thể hoạt động!",
      "sleep.future_time_error": "Thời gian báo thức phải là trong tương lai!",
      "sleep.alarm_notif_title": "Đã đến giờ thức giấc!",
      "sleep.alarm_notif_body": "Chào buổi sáng! Hãy thức dậy và bắt đầu một ngày mới.",
      "sleep.save_success": "Đã đặt báo thức thành công! Ứng dụng sẽ báo khi đến giờ.",
      "sleep.save_error": "Không thể cài đặt báo thức",
      "sleep.vitals_wake_up": "VITALS THỨC GIẤC",
      "sleep.shake_to_stop": "Lắc để dừng",
      "sleep.shake_desc": "Vận động cơ thể để tắt báo thức",
      "sleep.calibration": "TIẾN TRÌNH",
      "sleep.snooze": "Tạm dừng",
      "sleep.wake_up_success": "Chúc buổi sáng tốt lành! 🌅\nBạn đã tắt báo thức thành công!",
      "sleep.snooze_msg": "Báo thức sẽ reo lại trong 5 phút",
      "sleep.alarm_play_error": "Lỗi khi phát báo thức. Vui lòng thử lại.",
      "gym.completed": "Đã hoàn thành buổi tập!",
      "gym.amazing_effort": "Nỗ lực tuyệt vời hôm nay!",
      "gym.total_workout_time": "TỔNG THỜI GIAN TẬP",
      "gym.exercises_count": "Bài tập",
      "gym.total_sets": "Tổng số hiệp",
      "gym.total_reps": "Tổng số lần",
      "gym.kcal_burned": "Calo tiêu thụ",
      "gym.breakdown": "Chi tiết bài tập",
      "gym.sets_count": "Hiệp",
      "gym.reps_total": "Tổng lần",
      "gym.max": "Tối đa",
      "gym.back_dashboard": "Về trang chủ",
      "gym.discard": "Hủy hoạt động",
      "gym.save_error": "Lưu buổi tập thất bại. Vui lòng thử lại.",
      "yoga.namaste": "Namaste",
      "yoga.completed_prefix": "Bạn đã hoàn thành",
      "yoga.completed_flow_default": "bài tập của bạn",
      "yoga.mindfulness_stats": "Chỉ số thư giãn",
      "yoga.duration_label": "Thời lượng",
      "yoga.kcal_burned": "Calo tiêu thụ",
      "yoga.poses_count": "Tư thế",
      "yoga.save_btn": "Lưu phút tĩnh tâm",
      "yoga.discard_btn": "Hủy",
      "yoga.save_error": "Lỗi khi lưu hoạt động. Vui lòng thử lại.",
      "stretching.completed": "Hoàn thành giãn cơ!",
      "stretching.amazing_effort": "Cơ thể bạn sẽ cảm ơn bạn vì điều này!",
      "stretching.save_btn": "Lưu hoạt động giãn cơ",
    },
    en: {
      "chat.coach_title": "Health Coach",
      "chat.online_status": "● Online · Powered by Gemini",
      "chat.empty_title": "Hi! I am your AI Health Coach",
      "chat.empty_subtitle":
        "I have full access to your health data.\nAsk me anything about your health!",
      "chat.feature_activity": "Activity",
      "chat.feature_heart": "Heart Rate",
      "chat.feature_trend": "Trend",
      "chat.feature_health": "Health",
      "chat.feature_prompt_activity":
        "How has my activity been in the last 7 days?",
      "chat.feature_prompt_heart":
        "Is my average heart rate in the past week normal?",
      "chat.feature_prompt_trend": "Analyze my recent health trends.",
      "chat.feature_prompt_health":
        "Give me an overview of my current health status based on my data.",
      "chat.suggested_questions": "Suggested Questions",
      "chat.suggest": "Suggest",
      "chat.input_placeholder": "Ask about your health...",
      "chat.quota_exceeded_placeholder": "You reached today's chat limit...",
      "chat.clear_title": "Clear Chat",
      "chat.clear_confirm": "Delete all chat history?",
      "chat.delete": "Delete",
      "chat.error_prefix": "Sorry, an error occurred:",
      "chat.error_retry": "Please try again or check your network connection.",
      "chat.insight_highlights": "💡 Key highlights:",
      "chat.risk_high": "Risk: High",
      "chat.risk_medium": "Risk: Medium",
      "chat.risk_low": "Risk: Low",
      "chat.premium_feature": "AI Assistant (Health Chat)",
      "chat.suggest_q1": "How is my health this week?",
      "chat.suggest_q2": "How much should I exercise each day?",
      "chat.suggest_q3": "Is my average heart rate normal?",
      "chat.suggest_q4": "Am I meeting my daily step goal?",
      "chat.suggest_q5": "What should I eat to lose weight effectively?",
      "analysis.title_health": "Health",
      "analysis.title_analysis": "Analytics",
      "analysis.title_predict": "Prediction",
      "analysis.subtitle": "7-day health report",
      "analysis.loading": "Analyzing your health data with AI...",
      "analysis.na": "N/A",
      "analysis.activity_level": "Your activity level",
      "analysis.steps": "Steps",
      "analysis.last_7_days": "Last 7 Days",
      "analysis.kcal_burned": "Kcal Burned",
      "analysis.active_calories": "Active calories",
      "analysis.exercise_time": "Exercise Time",
      "analysis.minutes_active": "Minutes active",
      "analysis.heart_rate": "Heart Rate",
      "analysis.avg_daily_bpm": "Avg daily BPM",
      "analysis.premium_feature": "AI Analysis (Health Report)",
      "home.greeting": "Hello",
      "home.city_hcmc": "HCMC",
      "home.daily_tracking": "Daily Tracking",
      "home.sync_now": "Sync Now",
      "home.connect_fit": "Connect Fit",
      "home.tutorial_title": "Quick setup for new users",
      "home.tutorial_text":
        "Tap the highlighted Connect Fit button to link Google Fit and sync your daily steps, distance, and calories automatically.",
      "home.sleep": "Sleep",
      "home.water": "Water",
      "home.goal": "Goal",
      "home.ai_meals": "AI Meals",
      "home.ai_health_predict": "AI HEALTH PREDICT",
      "home.system_pulse": "System Pulse",
      "home.planner": "Planner",
      "home.today_schedules": "TODAY'S SCHEDULES",
      "home.manage": "Manage",
      "home.no_schedule_today": "No schedules for today. 🎉",
      "home.medication": "Medication",
      "home.medications": "medications",
      "home.show_less": "Show less",
      "home.show_more": "Show more",
      "home.types": "types",
      "home.time_slot": "Time Slot",
      "home.note": "Note",
      "home.latest_articles": "Latest Articles",
      "home.view_all": "View All",
      "home.health": "Health",
      "home.read_article": "Read Article",
      "tabs.home": "Home",
      "tabs.activity": "Activity",
      "tabs.analysis": "Analysis",
      "tabs.profile": "Profile",
      "profile.my": "My ",
      "profile.profile": "Profile",
      "profile.body_metrics": "Body Metrics",
      "profile.update": "Update",
      "profile.height": "Height",
      "profile.weight": "Weight",
      "profile.age": "Age",
      "profile.gender": "Gender",
      "profile.unit_cm": "cm",
      "profile.unit_kg": "kg",
      "profile.unit_years": "yrs",
      "profile.account": "Account",
      "profile.personal_data": "Personal Data",
      "profile.scan_medical_record": "Scan Medical Record",
      "profile.subscription_plan": "Subscription Plan",
      "auth.common.error": "Error",
      "auth.common.try_again": "Please try again.",
      "auth.verify.title": "Verify OTP",
      "auth.verify.subtitle": "A verification code has been sent to",
      "auth.verify.enter_code": "Enter 6-digit code",
      "auth.verify.confirm": "Confirm",
      "auth.verify.not_received": "Didn't receive the code? ",
      "auth.verify.resend": "Resend",
      "auth.verify.resend_after": "Resend after",
      "auth.verify.security_note":
        "OTP is valid for 5 minutes. Do not share this code with anyone.",
      "auth.verify.invalid_otp": "Please enter the full 6-digit OTP code.",
      "auth.verify.resend_success_title": "Code Resent",
      "auth.verify.resend_success_message":
        "A new OTP code has been sent to your email.",
      "auth.verify.resend_failed_title": "Resend Failed",
      "auth.verify.resend_failed_message": "Unable to resend OTP code.",
      "auth.verify_register.title": "Verify Registration OTP",
      "auth.verify_register.confirm_register": "Confirm & Register",
      "auth.verify_register.security_note":
        "OTP is valid for 10 minutes. Do not share this code with anyone.",
      "auth.verify_register.invalid_params":
        "Registration information is incomplete. Please try again.",
      "auth.verify_register.success_title": "Success",
      "auth.verify_register.success_message":
        "Your account has been created! Please provide some basic health metrics.",
      "auth.verify_register.ok": "OK",
      "auth.verify_register.create_failed":
        "An error occurred while creating your account.",
      "auth.reset.title": "Set New Password",
      "auth.reset.subtitle":
        "Create a new password for your account. Choose a password that is strong and memorable.",
      "auth.reset.new_password": "New Password",
      "auth.reset.new_password_placeholder": "Enter new password",
      "auth.reset.confirm_password_placeholder": "Re-enter password",
      "auth.reset.password_not_match": "Passwords do not match",
      "auth.reset.requirements": "Password requirements:",
      "auth.reset.requirement_min_6": "At least 6 characters",
      "auth.reset.requirement_uppercase":
        "Contains uppercase letter (recommended)",
      "auth.reset.requirement_number": "Contains number (recommended)",
      "auth.reset.confirm_button": "Confirm Password Reset",
      "auth.reset.password_min_length":
        "Password must be at least 6 characters.",
      "auth.reset.password_mismatch": "Password confirmation does not match.",
      "auth.reset.success_title": "Success",
      "auth.reset.success_message":
        "Your password has been reset successfully. Please sign in again.",
      "auth.reset.failed_title": "Reset Failed",
      "auth.reset.invalid_otp": "Invalid or expired OTP code.",
      "auth.reset.strength_weak": "Weak",
      "auth.reset.strength_medium": "Medium",
      "auth.reset.strength_strong": "Strong",
      "auth.reset.strength_very_strong": "Very Strong",
      "auth.register.subtitle": "Join Healthcare Now today",
      "auth.register.full_name_label": "Full Name",
      "auth.register.full_name_placeholder": "John Doe",
      "auth.register.confirm_password_label": "Confirm Password",
      "auth.register.validation_all_fields": "Please fill in all fields",
      "auth.register.validation_password_mismatch": "Passwords do not match",
      "auth.register.failed_title": "Registration Failed",
      "auth.register.email_exists":
        "This email is already registered. Please use a different email address.",
      "auth.register.send_otp_failed":
        "Something went wrong while sending OTP.",
      "auth.register.have_account": "Already have an account? ",
      "auth.forgot.title": "Forgot Password",
      "auth.forgot.subtitle":
        "Enter your registered email address. We will send a verification code to your email.",
      "auth.forgot.validation_email_required":
        "Please enter your email address.",
      "auth.forgot.send_failed_title": "Failed to Send Code",
      "auth.forgot.send_failed_message":
        "Unable to send OTP. Please try again.",
      "auth.forgot.send_code": "Send Verification Code",
      "auth.forgot.back_login": "Back to Sign In",
      "auth.login.subtitle": "Your Complete Digital Health Companion",
      "auth.login.email_label": "Email Address",
      "auth.login.email_placeholder": "example@email.com",
      "auth.login.password_label": "Password",
      "auth.login.sign_in": "Sign In",
      "auth.login.forgot_password": "Forgot Password?",
      "auth.login.or": "OR",
      "auth.login.continue_google": "Continue with Google",
      "auth.login.no_account": "Don't have an account? ",
      "auth.login.sign_up": "Sign Up",
      "auth.login.validation_missing": "Please enter email and password",
      "auth.login.failed_title": "Login Failed",
      "auth.login.failed_message": "Check your credentials and try again.",
      "auth.login.google_failed_title": "Google Login Failed",
      "auth.login.google_token_error": "Could not get Google ID Token",
      "auth.login.google_error_title": "Google Login Error",
      "settings.title": "Settings",
      "settings.account": "ACCOUNT",
      "settings.personal_info": "Personal Info",
      "settings.notifications": "Notifications",
      "settings.change_password": "Change Password",
      "settings.security_privacy": "Security & Privacy",
      "settings.preferences": "PREFERENCES",
      "settings.dark_mode": "Dark Mode",
      "settings.language": "Language",
      "settings.logout": "Log Out",
      "settings.premium": "Premium Member",
      "settings.new_user": "New User",
      "settings.upload_success_title": "Success",
      "settings.upload_success_message": "Avatar updated successfully!",
      "settings.upload_error_title": "Error",
      "settings.upload_error_message": "Failed to upload avatar.",
      "settings.language_pick_message": "Choose your preferred language",
      "settings.language_confirm_title": "Confirm language change",
      "settings.language_confirm_message":
        "The app will restart to apply the selected language.",
      "settings.confirm": "Confirm",
      "settings.cancel": "Cancel",
      "notifications.title": "Notifications",
      "notifications.processing": "Processing...",
      "notifications.mark_all_read": "Mark All Read",
      "notifications.tab_unread": "Unread",
      "notifications.tab_read": "Read",
      "notifications.empty": "No notifications yet.",
      "notifications.success_title": "Success",
      "notifications.success_message":
        "Exercise reminder notification sent to your phone!",
      "notifications.error_title": "Error",
      "notifications.error_message": "Unable to send test notification.",
      "notifications.mark_all_error": "Unable to mark all as read.",
      "security.title": "Security & Privacy",
      "security.account_auth_section": "ACCOUNT & AUTHENTICATION",
      "security.change_password": "Change Password",
      "security.change_password_subtitle":
        "Regularly update your password to secure your account",
      "security.change_email": "Change Email",
      "security.change_email_subtitle": "Update your login email address",
      "security.biometric": "Biometric Authentication",
      "security.biometric_subtitle":
        "Use fingerprint or Face ID instead of OTP",
      "security.auto_google_fit": "Auto Connect Google Fit",
      "security.auto_google_fit_subtitle":
        "Skip confirmation prompts when syncing health data",
      "security.security_alerts_section": "SECURITY ALERTS",
      "security.login_alert": "Strange Login Alert",
      "security.login_alert_subtitle":
        "Receive notifications and password change request if a new device logs in",
      "security.data_account_section": "DATA & ACCOUNT",
      "security.export_google_fit": "Export Google Fit Data",
      "security.export_google_fit_subtitle": "Download data in JSON/XML format",
      "security.privacy_policy": "Privacy Policy",
      "security.privacy_policy_subtitle":
        "View security policy and terms of service",
      "security.delete_account": "Delete Account",
      "security.delete_account_subtitle":
        "Permanently disable your user account",
      "security.hero_title": "Your account is protected",
      "security.hero_subtitle":
        "Manage access rights and personal information security.",
      "security.notification": "Notification",
      "security.auto_fit_enabled":
        "Auto Google Fit connect is enabled. You won't be asked again.",
      "security.auto_fit_disabled":
        "Auto Google Fit connect is disabled. You'll need to confirm next time.",
      "security.delete_confirm_title": "⚠️ Delete Account",
      "security.delete_confirm_message":
        "This action will permanently disable your account. You won't be able to log in again. Are you sure you want to delete your account?",
      "security.delete_confirm_button": "Delete Permanently",
      "security.delete_success_message": "Your account has been disabled.",
      "security.export_format_title": "Export Data Format",
      "security.export_format_message":
        "What format would you like to download your Google Fit data in?",
      "security.export_json": "JSON",
      "security.export_xml": "XML",
      "security.export_json_message": "JSON data is downloading...",
      "security.export_xml_message": "XML data is downloading...",
      "security.policy_title": "Privacy & Policy",
      "security.policy_content":
        "1. Data Collection: We only collect Google Fit data to provide health charts and analysis.\n2. Security: Your data is safely encrypted.\n3. Your Rights: You have the right to request complete data deletion at any time.",
      "security.feature_developing": "Feature under development.",
      "security.cancel": "Cancel",
      "security.error_no_data": "No health data found to export.",
      "security.sharing_unavailable": "Sharing is not available on this device.",
      "security.error": "Error",
      "change_password.title": "Change Password",
      "change_password.step1_subtitle":
        "Enter your current password to receive a verification OTP.",
      "change_password.step2_subtitle":
        "We've sent a 6-digit OTP to your email. Please enter it below.",
      "change_password.step3_subtitle":
        "Now enter your new password to complete the update.",
      "change_password.current_password": "Current Password",
      "change_password.password_placeholder": "••••••••",
      "change_password.forgot_password": "Forgot Password?",
      "change_password.send_otp": "Send OTP",
      "change_password.verify_identity": "Verify Your Identity",
      "change_password.enter_code":
        "Enter the 6-digit code sent to your email ",
      "change_password.resend_code_in": "Resend code in ",
      "change_password.resend_otp": "Didn't receive the code? Resend OTP",
      "change_password.verify_now": "Verify Now",
      "change_password.new_password": "New Password",
      "change_password.confirm_password": "Confirm New Password",
      "change_password.update_password": "Update Password",
      "change_password.error": "Error",
      "change_password.enter_current": "Please enter your current password",
      "change_password.profile_not_found": "User profile or email not found",
      "change_password.send_otp_failed":
        "Failed to send OTP. Check your current password.",
      "change_password.fill_all_fields": "Please fill in all fields",
      "change_password.profile_not_loaded":
        "User profile not loaded. Please try again.",
      "change_password.passwords_not_match": "Passwords do not match",
      "change_password.success": "Success",
      "change_password.success_message":
        "Password has been changed successfully!",
      "change_password.change_failed":
        "Invalid OTP or failed to change password.",
      "change_password.resend_success":
        "A new OTP has been sent to your email.",
      "change_password.resend_failed": "Failed to resend OTP.",
      "change_password.invalid_otp": "Please enter 6-digit OTP",
      "change_password.ok": "OK",
      "change_email.title": "Change Email",
      "change_email.step1_subtitle": "Update your new email to continue using our services.",
      "change_email.step2_subtitle": "Please enter the OTP sent to your new email address.",
      "change_email.new_email": "New Email",
      "change_email.email_placeholder": "example@email.com",
      "change_email.current_password": "Confirm Password",
      "change_email.password_placeholder": "••••••••",
      "change_email.send_otp": "Get OTP",
      "change_email.verify_now": "Confirm Change",
      "change_email.error": "Error",
      "change_email.invalid_email": "Invalid email format",
      "change_email.enter_password": "Please enter your password to confirm",
      "change_email.send_otp_failed": "Could not send OTP to this email.",
      "change_email.success": "Success",
      "change_email.success_message": "Your email has been changed successfully!",
      "change_email.change_failed": "Invalid OTP or email already exists.",
      "change_email.google_title": "Change Google Email",
      "change_email.google_subtitle": "You are logged in with Google. Please select a new Google account to change your email.",
      "change_email.google_btn": "Select New Google Account",
      "change_email.google_success": "Google email updated successfully!",
      "change_email.google_failed": "Could not change Google email.",
      "personal_data.title": "Personal Data",
      "personal_data.info_text":
        "Below is your synced Google Fit data for today ({date}).\nThis section uses movement time from Google Fit and does not depend on in-app exercise logs.",
      "personal_data.loading": "Loading health metrics...",
      "personal_data.error": "Failed to load health data.",
      "personal_data.steps": "Steps",
      "personal_data.distance": "Distance",
      "personal_data.heart_rate": "Heart Rate",
      "personal_data.resting_hr": "Resting HR",
      "personal_data.active_calories": "Active Calories",
      "personal_data.total_energy": "Total Energy",
      "personal_data.sleep_duration": "Sleep Duration",
      "personal_data.movement_time": "Movement Time",
      "personal_data.unit_steps": "steps",
      "personal_data.unit_bpm": "bpm",
      "personal_data.unit_kcal": "kcal",
      "personal_data.unit_km": "km",
      "personal_data.unit_h": "h",
      "personal_data.unit_m": "m",
      "personal_data.unit_meter": "m",
      "activity.hub": "Activity Hub",
      "activity.settings": "Settings",
      "activity.steps": "Steps",
      "activity.calories": "Calories",
      "activity.goal": "Goal",
      "activity.save_goals": "Save Goals",
      "activity.edit_goals": "Edit Goals",
      "activity.burned": "Burned",
      "activity.start": "Start Activity",
      "activity.running": "Running",
      "activity.outdoor": "Outdoor",
      "activity.gym": "Gym",
      "activity.indoor": "Indoor",
      "activity.stretching": "Stretching",
      "activity.yoga": "Yoga",
      "activity.set_goals": "Set Daily Goals",
      "activity.steps_goal": "Steps Goal",
      "activity.calories_goal": "Calories Goal (kcal)",
      "activity.steps_placeholder": "e.g. 10000",
      "activity.calories_placeholder": "e.g. 500",
      "activity.save": "Save",
      "activity.cancel": "Cancel",
      "activity.details_title": "Fitness Activities",
      "activity.aerobic": "Aerobic",
      "activity.flexibility": "Flexibility",
      "activity.recovery": "Recovery",
      "activity.strength": "Strength",
      "activity.total_dist": "Total Distance",
      "activity.avg_speed": "Avg. Speed",
      "activity.exercise_time": "Exercise Time",
      "activity.start_btn": "Start",
      "hydration.title": "Hydration",
      "hydration.today": "Today",
      "hydration.quick_add": "QUICK ADD",
      "hydration.recent_activity": "RECENT ACTIVITY",
      "hydration.view_all": "View All",
      "hydration.no_logs": "No logs today yet.",
      "hydration.goal": "Goal",
      "hydration.ml": "ml",
      "hydration.custom": "Custom",
      "sleep.title": "Sleep",
      "sleep.score": "SLEEP SCORE",
      "sleep.total_duration": "TOTAL DURATION",
      "sleep.deep_sleep": "DEEP SLEEP",
      "sleep.relaxing_sounds": "Relaxing Sounds",
      "sleep.view_all": "View All",
      "sleep.smart_alarm": "Smart Alarm",
      "sleep.excellent": "Excellent",
      "sleep.good": "Good",
      "sleep.fair": "Fair",
      "sleep.add_alarm": "Add Alarm",
      "sleep.no_alarms": "No alarms set yet",
      "sleep.rain": "Rain",
      "sleep.forest": "Forest",
      "sleep.wave": "Wave",
      "meal.title": "Meal Schedule",
      "meal.ai_nutritionist": "AI Nutritionist",
      "meal.scientific_diet_planning": "Scientific Diet Planning",
      "meal.my_meal_plan": "My Meal Plan",
      "meal.activities": "Activities",
      "meal.generate_plan": "Generate Plan",
      "meal.generating": "Generating...",
      "meal.breakfast": "Breakfast",
      "meal.lunch": "Lunch",
      "meal.dinner": "Dinner",
      "meal.snacks": "Snacks",
      "meal.estimated_calories": "Estimated Calories",
      "meal.no_history": "No history yet",
      "meal.quota_exceeded": "Meal plan quota exceeded for today",
      "meal.running": "Running",
      "meal.walking": "Walking",
      "meal.yoga": "Yoga",
      "meal.gym": "Gym/Weights",
      "meal.cycling": "Cycling",
      "meal.delete_history": "Delete from history",
      "meal.clear_all": "Clear All",
      "meal.delete_confirm": "Delete this meal plan from history?",
      "meal.clear_all_confirm": "Delete all saved AI meal history?",
      "meal.cancel": "Cancel",
      "meal.delete": "Delete",
      "meal.clear": "Clear",
      "meal.personal_metrics": "Personal Metrics",
      "meal.weight": "Weight",
      "meal.height": "Height",
      "meal.age": "Age",
      "meal.gender": "Gender",
      "meal.steps_label": "Steps",
      "meal.distance_label": "Distance",
      "meal.male": "Male",
      "meal.female": "Female",
      "meal.choose_activity": "Choose Activity",
      "meal.select_at_least_one": "Please select at least one activity",
      "meal.plan_history": "Plan History",
      "meal.saved_plans": "saved plans",
      "meal.no_saved_plans": "No saved meal plans yet",
      "meal.generate_automatic":
        "Generate a plan and it will appear here automatically",
      "meal.past_plan": "Past Plan",
      "meal.view_btn": "View",
      "meal.update_stats": "Update your stats for precision",
      "meal.restricted_ingredients": "Restricted Ingredients",
      "meal.ai_exclude": "AI will exclude",
      "meal.total_tdee": "Total Daily Energy (TDEE)",
      "meal.protein": "Protein",
      "meal.carbs": "Carbs",
      "meal.fat": "Fat",
      "meal.quantified_meals": "Quantified Meals",
      "meal.recalculate": "Recalculate Metrics",
      "article.title": "All Articles",
      "article.loading": "Loading...",
      "article.health": "Health",
      "article.no_articles": "No articles yet.",
      "article.error": "Error fetching articles",
      "article.details": "Article Details",
      "article.back": "Back",
      "article.not_found": "Article not found",
      "article.read_time": "min read",
      "article.by": "by",
      "article.ai_expert": "Nutrition Expert",
      "article.summary": "Summary",
      "article.content": "Content",
      "article.no_content": "No detailed content available",
      "article.bookmark": "Save",
      "article.bookmarked": "Saved",
      "schedule.title": "Schedule",
      "schedule.manage": "Manage Schedule",
      "schedule.add": "Add Schedule",
      "schedule.date": "Date",
      "schedule.time": "Time",
      "schedule.description": "Description",
      "schedule.save": "Save",
      "schedule.cancel": "Cancel",
      "schedule.confirm_delete": "Delete this schedule?",
      "sleep.alarm": "Alarm",
      "sleep.alarms": "Alarms",
      "sleep.set_alarm": "Set Alarm",
      "sleep.edit_alarm": "Edit Alarm",
      "stretching.duration": "Duration",
      "stretching.start": "Start",
      "stretching.end": "End",
      "stretching.summary": "Stretching Summary",
      "subscription.title": "Subscription Plan",
      "subscription.expired": "Expired",
      "subscription.days_left": "days left",
      "medical.scan": "Medical Scan",
      "medical.upload": "Upload",
      "medical.delete": "Delete",
      "medical.no_records": "No records yet",
      "medical.error": "Upload Error",
      "medication.title": "Medication Schedule",
      "medication.add": "Add Medication",
      "medication.edit": "Edit",
      "medication.delete": "Delete",
      "medication.name": "Medication Name",
      "schedule.active_schedules": "active schedules",
      "schedule.done": "Done",
      "schedule.select_all": "Select All",
      "schedule.delete_count": "Delete ({count})",
      "schedule.details": "Details",
      "schedule.more": "more",
      "schedule.new_subtitle": "Design your personalized fitness routine",
      "schedule.select_type": "SELECT ACTIVITY TYPE",
      "schedule.set_frequency": "SET FREQUENCY",
      "schedule.daily": "Daily",
      "schedule.weekly": "Weekly",
      "schedule.custom": "Custom",
      "schedule.select_days": "SELECT DAYS",
      "schedule.set_time": "SET TIME",
      "schedule.set_goal": "SET GOAL",
      "schedule.goal_required":
        "Goal is required. Please enter your training goal.",
      "schedule.missing_goal": "Missing goal",
      "schedule.missing_goal_msg":
        "You need to enter a goal before creating a schedule.",
      "schedule.missing_days": "Missing days",
      "schedule.missing_days_msg": "Please select at least 1 day.",
      "schedule.success_msg": "Workout schedule saved successfully!",
      "schedule.error_msg": "Failed to save schedule. Please try again.",
      "schedule.creating": "Creating...",
      "schedule.create": "Create Schedule",
      "running.gps_active": "GPS ACTIVE",
      "running.elapsed_time": "ELAPSED TIME",
      "running.save_error": "Errors during saving! Please try again.",
      "running.permission_error": "Permission needed to save your route image.",
      "running.share_title": "Check out my run on HealthCareNow!",
      "running.save_success":
        "Awesome! Route Map has been saved to your Photos/Gallery.",
      "running.completed": "Run Completed!",
      "running.completed_subtitle_map": "Awesome job. Here is your route.",
      "running.completed_subtitle_trophy":
        "Awesome job. You're getting stronger everyday.",
      "running.total_distance": "TOTAL DISTANCE",
      "running.share": "Share / Save Route Map",
      "running.discard": "Discard",
      "subscription.plans_subtitle":
        "Unlock your full health potential with Premium.",
      "subscription.active_plan": "ACTIVE PLAN",
      "subscription.recommended": "RECOMMENDED",
      "subscription.all_features_active": "All features are activated",
      "subscription.complete_upgrade": "Complete Upgrade",
      "subscription.billed_once": "Billed once",
      "subscription.lifetime_unlocked": "Lifetime access unlocked",
      "subscription.pay_once": "Pay once, use forever",
      "subscription.select_method": "Select Payment Method",
      "subscription.confirm_pay": "Confirm & Pay",
      "subscription.secure_ssl": "SECURE SSL ENCRYPTION",
      "subscription.feature_analysis": "Unlimited AI Health Analysis",
      "subscription.feature_meals": "Unlimited AI Meals & Diet Plans",
      "subscription.feature_chat": "Unlimited AI Health Chat",
      "subscription.feature_scans": "Unlimited Medical Record Scans",
      "subscription.feature_reports": "Advanced Biometric Reports",
      "subscription.feature_basic_tracking": "Basic Activity Tracking",
      "subscription.feature_limited_insights": "Basic Health Insights",
      "subscription.feature_standard_support": "Standard Support",
      "premium.limit_reached": "Limit Reached",
      "premium.upgrade_now": "Upgrade Now",
      "premium.later": "Later",
      "premium.description": "You've reached the usage limit for {featureName}. Upgrade to Premium to unlock unlimited access and improve your health journey.",
      "premium.feature_ai_analysis": "Unlimited AI Analysis",
      "premium.feature_ai_analysis_sub": "Deep dive into every metric, every day.",
      "premium.feature_ai_assistant": "24/7 Health Assistant",
      "premium.feature_ai_assistant_sub": "Access your medical AI assistant anywhere.",
      "premium.feature_health_plans": "Personal Health Plans",
      "premium.feature_health_plans_sub": "Daily routines tailored specifically for you.",
      "medical.scan_title": "Scan Medical Record",
      "medical.ai_feature_name": "AI Medical Scan",
      "medical.no_image": "No image selected",
      "medical.analyzing": "AI is analyzing records...",
      "medical.gallery": "Gallery",
      "medical.take_photo": "Take Photo",
      "medical.diagnosis": "Diagnosis",
      "medical.medications_count": "Prescribed Medications ({count})",
      "medical.medication_times": "Medication Times:",
      "medical.forbidden_foods_list": "Forbidden Food List",
      "medical.schedule_reminders": "Schedule Reminders",
      "medical.history": "Medical History",
      "medical.active_medication": "Active Medication",
      "medical.expired_label": "Expired",
      "medical.reminders_disabled":
        "All reminders for this record have been removed.",
      "medical.reminders_enabled": "Medication reminders have been recreated.",
      "medical.duration": "Duration:",
      "medical.disable": "Disable",
      "medical.enable": "Enable",
      "medical.details": "Details",
      "medical.expire_btn": "Expire",
      "medical.forbidden_foods_btn": "Forbidden Foods",
      "medical.permission": "Permission",
      "medical.notice": "Notice",
      "medical.save_error": "Could not save record or create reminders.",
      "medical.confirm": "Confirm",
      "medical.expire_confirm_msg": "Mark this record as expired/recovered?",
      "medical.cancel_action": "Cancel",
      "medical.expire_success": "Record expired and all reminders cleaned up.",
      "medical.expire_error":
        "Could not fully update status or clean up reminders.",

      "common.mon": "Mon",
      "common.tue": "Tue",
      "common.wed": "Wed",
      "common.thu": "Thu",
      "common.fri": "Fri",
      "common.sat": "Sat",
      "common.sun": "Sun",
      "common.already_premium": "Already Premium",
      "common.already_premium_msg": "You are already a Premium member! 🎉",
      "common.failed_create_order": "Failed to create payment order.",
      "common.payment_success":
        "Payment successful! Your account is being upgraded.",
      "common.cancelled": "Cancelled",
      "common.payment_cancelled": "Payment was cancelled.",

      "meal.bmr": "Basal Metabolic Rate (BMR)",
      "meal.kcal": "kcal",
      "meal.dose": "dose",
      "subscription.premium_lifetime": "Premium Lifetime Plan",
      "subscription.life_period": "LIFE",
      "subscription.select_payment": "Select Payment Method",
      "subscription.apple_pay": "Apple Pay",
      "subscription.google_pay": "Google Pay",
      "subscription.payos_method": "PayOS (QR / Bank Transfer)",
      "subscription.secure_gateway": "Fast & Secure Payment Gateway",
      "subscription.all_vn_banks": "All Vietnamese Banks",
      "subscription.vietqr": "VietQR",
      "subscription.payos_checkout": "PayOS Checkout",
      "subscription.browser_unavailable": "Internal browser unavailable.",
      "subscription.open_browser": "Open in Browser",
      "subscription.price_free": "$0",
      "subscription.forever": "/ forever",
      "subscription.one_time": "/ one-time",
      "subscription.price_premium": "10,000đ",
      "medical.retake": "Retake",
      "medical.close": "Close",
      "medical.unit_dose": "dose",
      "running.duration": "DURATION",
      "running.avg_pace": "AVG PACE",
      "running.save_activity": "Save Activity",
      "metrics.title": "Your Metrics",
      "metrics.subtitle": "Help us personalize your health journey",
      "metrics.full_name": "Full Name",
      "metrics.weight": "Weight",
      "metrics.height": "Height",
      "metrics.sleep_goal": "Sleep Goal",
      "metrics.steps_goal": "Steps Goal",
      "metrics.calories_goal": "Calories Goal",
      "metrics.dob": "Date of Birth",
      "metrics.gender": "Gender",
      "metrics.male": "Male",
      "metrics.female": "Female",
      "metrics.other": "Other",
      "metrics.activity_level": "Activity Level",
      "metrics.activity_sedentary": "Sedentary",
      "metrics.activity_lightly": "Lightly Active",
      "metrics.activity_moderately": "Moderately Active",
      "metrics.activity_very": "Very Active",
      "metrics.complete": "Complete Profile",
      "metrics.saving": "Saving...",
      "metrics.skip": "I'll do this later (Go to Home)",
      "metrics.error": "Error",
      "metrics.fill_required": "Please fill in weight and height",
      "metrics.success": "Success",
      "metrics.save_success": "Profile metrics saved! Welcome to Healthcare Now.",
      "metrics.get_started": "Get Started",
      "metrics.save_failed": "Failed to save metrics.",
      "metrics.invalid_input": "Invalid data. Please check again.",
      "sleep.alarm_setup_title": "Set Alarm",
      "sleep.smart_alarm_desc": "Wake up in light sleep phase",
      "sleep.repeat_title": "REPEAT",
      "sleep.choose_ringtone": "CHOOSE RINGTONE",
      "sleep.start_sleeping": "Start Sleeping",
      "sleep.saving": "Saving...",
      "sleep.prediction_prefix": "If you sleep now, you will have",
      "sleep.prediction_suffix": "sleep duration",
      "sleep.every_day": "Every day",
      "sleep.once": "Once",
      "sleep.weekdays": "Weekdays",
      "sleep.weekends": "Weekends",
      "sleep.notif_permission_msg": "Please grant notification permission for the alarm to work!",
      "sleep.future_time_error": "Alarm time must be in the future!",
      "sleep.alarm_notif_title": "Wake up time!",
      "sleep.alarm_notif_body": "Good morning! Wake up and start a new day.",
      "sleep.save_success": "Alarm set successfully! The app will notify you when it's time.",
      "sleep.save_error": "Failed to set alarm",
      "sleep.vitals_wake_up": "VITALS WAKE-UP",
      "sleep.shake_to_stop": "Shake to Stop",
      "sleep.shake_desc": "Wake up your body to deactivate",
      "sleep.calibration": "CALIBRATION",
      "sleep.snooze": "Snooze",
      "sleep.wake_up_success": "Good morning! 🌅\nYou have successfully turned off the alarm!",
      "sleep.snooze_msg": "Alarm will ring again in 5 minutes",
      "sleep.alarm_play_error": "Error playing alarm. Please try again.",
      "gym.completed": "Workout Completed!",
      "gym.amazing_effort": "Amazing effort today!",
      "gym.total_workout_time": "TOTAL WORKOUT TIME",
      "gym.exercises_count": "Exercises",
      "gym.total_sets": "Total Sets",
      "gym.total_reps": "Total Reps",
      "gym.kcal_burned": "Kcal Burned",
      "gym.breakdown": "Exercise Breakdown",
      "gym.sets_count": "Sets",
      "gym.reps_total": "Reps Total",
      "gym.max": "Max",
      "gym.back_dashboard": "Back to Dashboard",
      "gym.discard": "Discard Activity",
      "gym.save_error": "Failed to save workout. Please try again.",
      "yoga.namaste": "Namaste",
      "yoga.completed_prefix": "You completed",
      "yoga.completed_flow_default": "your flow",
      "yoga.mindfulness_stats": "Mindfulness Stats",
      "yoga.duration_label": "Duration",
      "yoga.kcal_burned": "Kcal Burned",
      "yoga.poses_count": "Poses",
      "yoga.save_btn": "Save Mindful Minutes",
      "yoga.discard_btn": "Discard",
      "yoga.save_error": "Errors saving activity. Please try again.",
      "stretching.completed": "Stretching Completed!",
      "stretching.amazing_effort": "Your body will thank you for this!",
      "stretching.save_btn": "Save Stretching Activity",
    },
  };

  const t = (key: string, defaultText?: string): string => {
    return translations[language][key] || defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
